In [4]:
from google.colab import files
uploaded = files.upload()

Saving aapl.csv to aapl.csv
Saving amzn.csv to amzn.csv
Saving fb.csv to fb.csv
Saving goog.csv to goog.csv
Saving nflx.csv to nflx.csv

In [2]:
import pandas as pd

In [5]:
#b.
aapl = pd.read_csv('aapl.csv')
amzn = pd.read_csv('amzn.csv')
fb = pd.read_csv('fb.csv')
goog = pd.read_csv('goog.csv')
nflx = pd.read_csv('nflx.csv')

In [6]:
#c.
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'
nflx['ticker'] = 'NFLX'

In [7]:
#d.
faanf = pd.concat([aapl, amzn, fb, goog, nflx], ignore_index=True)
faanf.head()

         date      open      high       low     close    volume ticker
0  2018-01-02  166.9271  169.0264  166.0442  168.9872  25555934   AAPL
1  2018-01-03  169.2521  171.2337  168.6929  168.9578  29517899   AAPL
2  2018-01-04  169.2619  170.1742  168.8106  169.7426  22434597   AAPL
3  2018-01-05  170.1448  172.0381  169.7622  171.6751  23660018   AAPL
4  2018-01-08  171.0375  172.2736  170.6255  171.0375  20567766   AAPL

In [8]:
#e.
faanf.to_csv('faanf.csv', index=False)

In [9]:
#f.
faanf = pd.read_csv('faanf.csv')

#Convert date to datetime
faanf['date'] = pd.to_datetime(faanf['date'])

#Convert volume to integer
faanf['volume'] = faanf['volume'].astype(int)

#Sort by date and ticker
faanf = faanf.sort_values(by=['date', 'ticker']).reset_index(drop=True)

faanf.head(10)

        date       open       high        low      close    volume ticker
0 2018-01-02   166.9271   169.0264   166.0442   168.9872  25555934   AAPL
1 2018-01-02  1172.0000  1190.0000  1170.5100  1189.0100   2694494   AMZN
2 2018-01-02   177.6800   181.5800   177.5500   181.4200  18151903     FB
3 2018-01-02  1048.3400  1066.9400  1045.2300  1065.0000   1237564   GOOG
4 2018-01-02   196.1000   201.6500   195.4200   201.0700  10966889   NFLX
5 2018-01-03   169.2521   171.2337   168.6929   168.9578  29517899   AAPL
6 2018-01-03  1188.3000  1205.4900  1188.3000  1204.2000   3108793   AMZN
7 2018-01-03   181.8800   184.7800   181.3300   184.6700  16886563     FB
8 2018-01-03  1064.3100  1086.2900  1063.2100  1082.4800   1430170   GOOG
9 2018-01-03   202.0500   206.2100   201.5000   205.0500   8591369   NFLX